project:
  type: website
  output-dir: docs  

website:
  title: "Anous Ahmed"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Resume
        href: resume.pdf
    right:
      - icon: github
        href: "https://github.com/aahme102/Week-9-Exercise"   
        aria-label: GitHub

format:
  html:
    theme: sandstone
    mainfont: Arial
    monofont: "Courier New"
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    css: styles.css
    toc: false