project:
  type: website
  output-dir: docs

website:
  title: "Anous Ahmed"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Anous Ahmed Resume.pdf
        text: Resume

format:
  html:
    theme: sandstone
    mainfont: arial 
    fontsize: 1.5rem  
    fontcolor: “#0013d5” 
    linkcolor: “#ff33f0” 
    monofont: courier new 

editor: visual

